### ISSUE TITLE
installation: pip install doesn't install all dependent packages

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#11]
```console
pip install git+https://github.com/reanahub/reana-client.git
```

Doesn't work out of the box, the following packages are missing  `pyOpenSSL`, `rfc3987`, `webcolors` and `strict-rfc3339`

**Comment by tiborsimko** [comment]
Please add them to the `setup.py` with a FIXME note. Here are working versions on my laptop:

- pyOpenSSL==17.3.0
- rfc3987==1.3.7
- strict-rfc3339==0.7
- webcolors==1.7

**Comment by diegodelemos** [comment]
Closing as dependencies are defined in `setup.py`.
