### ISSUE TITLE
docs: token procedures

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-client#110]
After the addition of the user tokens, documentation needs to be updated to show how to get a token 
 and how to use them.

**Comment by diegodelemos** [comment]
Closing as user commands are on the way to be moved to `reana-server` https://github.com/reanahub/reana-server/issues/57.

**Comment by tiborsimko** [comment]
Still, we need to document in `reana-client` that users should do `export REANA_ACCESS_TOKEN=...` in their environments... Could come as part of #128.
