### ISSUE TITLE
yadage: nicer progress command

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#126]
Prettify progress display for Yadage workflows. Currently one gets:

```console
$ reana-client workflow status -w workflow.3
NAME       RUN_NUMBER   CREATED               STATUS     PROGRESS   COMMAND
workflow 3 2018-06-28T08:57:58 finished 2/2 sh -c 'echo
cm9vdCAtYiAtcSAnL2RhdGEvMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL2FuYWx5c2VzLzAwYThlOWUyLWJkNjktNGFkYy04ZmE3LWIxNzkwZWMwM2E2Ni95YWRhZ2VfaW5wdXRzL2NvZGUvZml0ZGF0YS5DKCIvZGF0YS8wMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAvYW5hbHlzZXMvMDBhOGU5ZTItYmQ2OS00YWRjLThmYTctYjE3OTBlYzAzYTY2L3dvcmtzcGFjZS9nZW5kYXRhL2RhdGEucm9vdCIsIi9kYXRhLzAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMC9hbmFseXNlcy8wMGE4ZTllMi1iZDY5LTRhZGMtOGZhNy1iMTc5MGVjMDNhNjYvd29ya3NwYWNlL2ZpdGRhdGEvcGxvdC5wbmciKSc=|base64
-d|sh'
```

(stemmed from https://github.com/reanahub/reana-workflow-engine-serial/pull/17#pullrequestreview-132753154)

**Comment by lukasheinrich** [comment]
Hi @tiborsimko, maybe this is rather the job of the workflow-controller? Consider the case of a non-CLI client such as CAP that also would like to interact with REANA purely via a REST API, it would be good if the client would not need to implement much logic on their side.

**Comment by tiborsimko** [comment]
Yes, I agree, e.g. in case of Yadage, each step in the workflow has a name, so `r-w-e-yadage` could send the visible command names to register as progress instead of base64-encoded string.
The `r-client` component could then simply return what was passed.

IOW, ticketised here (also for CWL) since this is a sort of client-visible issue, but it may be best to implement it elsewhere in the REANA component ecosystem...
