### ISSUE TITLE
REANA_TOKEN -> REANA_ACCESS_TOKEN

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#128]
It would be good to use `REANA_ACCESS_TOKEN` as the environment variable name.  It is more descriptive and it matches the CAP practices as well.

We may want to change the OpenAPI specs to use "access_token" everywhere for consistency. 

(stemmed from https://github.com/reanahub/reana-client/pull/103)

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-client/pull/136, https://github.com/reanahub/reana-server/pull/64, https://github.com/reanahub/reana-workflow-controller/pull/112, https://github.com/reanahub/reana-commons/pull/32.
