### ISSUE TITLE
cli: simplify workflow commands

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#131]
`reana-client workflow list` -> `reana-client workflows`
`reana-client workflow create` -> `reana-client new`
`reana-client workflow status` -> `reana-client status`
`reana-client workflow start` -> `reana-client run|submit|start` @reanahub/developers what's the last pick for this keyword?
`reana-client analysis validate` -> `reana-client validate`
`reana-client status` -> `reana-client ping`

**Comment by tiborsimko** [comment]
@diegodelemos We discussed using `submit` last time, but I guess `start` may be even better. Especially if we shall later introduce a new `stop` command. 

(I like using complementary word pairs that go well together, i.e. create/delete, start/stop, rather then create/stop, say.  The word pair verb chain `create -> start -> stop -> delete` is easily intuitively understood and remembered, I think. Recalling a good old chapter "The Power of Variable Names" in Steve McConnell's "Code Complete" book...)

BTW see also Pachyderm's CLI commands: http://docs.pachyderm.io/en/latest/pachctl/pachctl.html
