### ISSUE TITLE
cli: configurable spec file name 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#14]
Currently `.reana.yaml` looks hardcoded, see for example `reana_yaml_file_path`.

It would be useful to allow specifying it from CLI.  For example:

```console
$ reana-client -f reana-spec-quick-test.yaml run`
$ reana-client -f reana-spec-trying-out-different-weights.yaml  run`
[...]
$ reana-client -f reana-spec-final-run.yaml run`
```

This is similar to how e.g. `docker-compose -f ...` permits to specify any wanted file to serve as `Dockerfile`.

Note that this would be handy not only when we have several different parameter sets for the given workflow, but also for testing several different workflow engines, say Yadage and CWL, on the same code base.

**Comment by tiborsimko** [comment]
@hjhsalo You may want to look at this under the "no hardcoded strings" umbrella...

**Comment by tiborsimko** [comment]
BTW, we may want to ponder making the REANA spec file to be a required argument to `run`, rather than optional `-f` one, as this is more of a use case similar to `condor_submit` rather than `.travis.yml`.

**Comment by hjhsalo** [comment]
PR #16 implements -f flag as optional.
Let's not close this yet, since it might be a good idea to have fileinput as a mandatory argument instead of optional flag.

**Comment by tiborsimko** [comment]
Keeping it optional for REANA v0.2.0 release.
