### ISSUE TITLE
installation: Python 3 support

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#17]
`reana-client` currently does not work with Python 3.  One has to use Python 2. It would be good to make it Python 2.3 compatible.  Note that this requires some changes in Yadage.

**Comment by diegodelemos** [comment]
waiting for https://github.com/diana-hep/yadage-schemas/issues/12 @lukasheinrich

**Comment by diegodelemos** [comment]
Blocked by https://github.com/reanahub/reana/issues/40#issuecomment-368786668
