### ISSUE TITLE
pip install reana-client[cwl,serial,yadage]

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#174]
As the number of supported REANA workflow engines grows, it is useful to offer an option to users to install only some workflow engine libraries that the given user uses. E.g. only Yadage and no CWL, which can come handy to both (1) save some disk space from dependencies and (2) ease possible incompatibility situations such as older CWL with Python 3.7.

The user would do: 

```console
$ pip install reana-client[yadage]
```

which would only install Yadage-related optional dependencies.

P.S. We should still consider which "popular" dependencies should be installed by default when people do not specify anything... Probably all three engines for now.

**Comment by diegodelemos** [comment]
Work started in https://github.com/reanahub/reana-client/pull/176.

**Comment by tiborsimko** [comment]
Tested AppImage based installation, which works well, so closing this issue in favour of https://github.com/reanahub/reana-client/issues/390.
