### ISSUE TITLE
cli: filter does not work

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#208]
Currently `--filter` filters by column, but no matter which column you select, it shows the content of the first one:
```console
$ reana-client workflows --filter STATUS
STATUS
workflow
myanalysis
workflow
```

We should either fix it or disable it for the time being since we will take more benefit from a row filtering more than the column one (for instance to filter out `deleted` workflows).

**Comment by tiborsimko** [comment]
We have had renamed the CLI option to `--format`, i.e. printing only the wanted columns in the ouput format.
