### ISSUE TITLE
spec: add support for specifying some `reana run` operational arguments in spec file

### ISSUE THREAD

**Issue by hjhsalo** [reanahub/reana-client#21]
Following the discussion in https://github.com/reanahub/reana-client/pull/16 it might be good to have a way to specify the "operational" argumens as CLI options (e.g. `reana run --user "jdoe" --organization "acme-dep"`), plus have a way of storing them in the spec files for later archiving.

What do you think, is this something that one would want to preserve in REANA specifications file or something that should definitely not be there?

Implementation would probably be something like:
* a key `user` in spec file where CLI reads it from.
* `user`-value passed to the CLI would take preference if it exists.
* Regarding to passing `user`-value as env_var (currently not supported), which one would take preference, the env_var or the cli-submitted one?
* If no `user`-value exists in spec file, nor one is passed to CLI and env_var doesn't specify it either, default value defined in config.py would be used.

**Comment by diegodelemos** [comment]
Superseded by https://github.com/reanahub/reana-client/issues/152.
