### ISSUE TITLE
cli: complete command list 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#22]
In order to better showcase the potential of `reana-client`, let's create a relatively complete list of all commands we are sure to implement.  For example:

The command list could look like:

- validate
- initialise
- seed-working-space
- list-working-space
- submit / run
- get-status
- list-output-files

An example session could look like:

```
$ reana-client validate myanalysis.yaml
OK
$ reana-client initialise
624ae7fb-d8be-440a-a07e-f3c7b0850515 initialised
$ reana-client seed-working-space myinputdata.tar.gz
OK
$ reana-client seed-working-space http://example.org/anotherfile.tar.gz
OK
$ reana-client list-working-space myinputdata.tar.gz
.uuid
.profile
data/myinputdata.tar.gz
data/anotherfile.tar.gz
results/
logs/
$ reana-client run myanalysis.yaml --analysis 624ae7fb-d8be-440a-a07e-f3c7b0850515
624ae7fb-d8be-440a-a07e-f3c7b0850515 submitted
$ reana-client submit myanalysis.yaml
Workflow 624ae7fb-d8be-440a-a07e-f3c7b0850515 submitted.
$ reana-client get-status --analysis 624ae7fb-d8be-440a-a07e-f3c7b0850515
624ae7fb-d8be-440a-a07e-f3c7b0850515 running
$ sleep 900
$ reana-client get-status --analysis 624ae7fb-d8be-440a-a07e-f3c7b0850515
624ae7fb-d8be-440a-a07e-f3c7b0850515 finished
$ reana-client list-output-files --analysis 624ae7fb-d8be-440a-a07e-f3c7b0850515
results/myresults.csv
results/myplot1.png
results/myplot2.png
$ reana-client get-output-file --analysis-id 624ae7fb-d8be-440a-a07e-f3c7b0850515 --file myplot1.png
myplot1.png
$ reana-client list-output-files --analysis-id 624ae7fb-d8be-440a-a07e-f3c7b0850515
Error: NotImplemented
```

Just an illustration; to be mused IRL.

**Comment by tiborsimko** [comment]
Results of IRL musings with @diegodelemos @hjhsalo:
All commands will follow the same structure:

```
$ reana-client <resource> <action> [--opt1 val1] [--opt2 val2] <param1> <param2>
```

The resource naming will echo the REANA spec file structure naming https://github.com/reanahub/reana-client/issues/10#issuecomment-338906229.

Example:

```
$ reana-client --help

   --help
   --version

   analysis
       validate
       rerun
       preserve

   code
       list
       get
       put

   inputs
       list
       get
       put

   workflow
       create
       start
       stop
       status
       resume
       logs
       destroy
       list

   outputs
       list
       get
       put
```

The **analysis** resource will focus on the highest level. Checking validity means checking spec file conformance, existence of inputs, existence of Docker images, data referenced via URLs, etc. Run verified analysis is a syntactic sugar enveloping multiple lower-level CLI actions (create working space, upload input files by parsing REANA spec file, run workflow, get output files into current working directory). Preserve option will later preserve REANA-compatible analysis in CAP.

The **inputs** resource will offer ways to upload files to working directory (`./inputs`), list and retrieve its content.

The **code** resource will offer ways to upload software files into working directory (`./code`), list and retrieve its content.

The **workflow** resource will offer actions centred around running workflows on given input data, with the given code, using the given runtime environment. Starting, pausing, resuming and stopping of workflows. Enquiring about status of workflows and its logs. List all started/submitted/finished workflows. Offer an option to associate human-friendly name to UUIDs.  (Possibly using docker-style names like `nervous_montalcini` if users don't specify a name.)

The **outputs** resource will offer ways to download files from the working directory (`./outputs`), list and retrieve its content.

The usage scenario would go like:

```
$ reana-client analysis verify
$ reana-client workflow create --name mytest
$ reana-client inputs put mytest mydata.csv
$ reana-client inputs list mytest
$ reana-client code put mytest mycode.py
$ reana-client workflow start
$ reana-client workflow status
$ sleep 300
$ reana-client workflow status
$ reana-client outputs get plot.png
$ reana-client workflow destroy
```

Prefer using complementary action verbs, such as create/destroy, start/stop, upload/download, get/set.
(Huh for put/get seen above!)

Think of machine-consumable output formats. For example return human-friendly text by default, return machine-friendly JSON when `--json` general option is used.

Implement only necessary options now, but hint at the full structure with raise NotImplemented exceptions for future-looking options.

**Comment by tiborsimko** [comment]
P.S. The documentation is to be cleaned, obviously. E.g. using `mytest` in the above scenario is not consistent everywhere (argument? option? silent?), e.g. get/put alluded to above...

**Comment by diegodelemos** [comment]
Shall we close since there  has been no reactions so far? Despite the fact that it is not very clear how to use the `workflow` name in subsequent commands, I think we are ready to go.

**Comment by tiborsimko** [comment]
```console
$ export REANA_SERVER_URL=localhost
$ reana-client workflow list
  mythirdtest <uuid3> running
  mysecondtest <uuid2> failed
  myfirsttest <uuid1> finished
$ reana-client workflow create --name mytest
$ export REANA_WORKON=mytest # possibly use .rc cache later
$ reana-client workflow list
* mytest <uuid1> created
  mythirdtest <uuid3> running
  mysecondtest <uuid2> failed
  myfirsttest <uuid1> finished
$ reana-client inputs set min_year 1990
$ reana-client inputs get min_year
1990
$ reana-client inputs set max_year 2001
$ reana-client inputs list --parameters
min_year
max_year
$ reana-client inputs upload mydata.csv
$ reana-client inputs list --files
mydata.csv
$ reana-client inputs list --json
{'files': ['mydata.csv'],
 'parameters': [
    {'min_year': '1990'},
    {'max_year': '2001'}
 ]
}
$ reana-client code upload mycode.py
$ reana-client workflow status
created
$ reana-client workflow start
$ reana-client workflow status
running
$ reana-client workflow status --name mytest
running
$ reana-client workflow status --name mythirdtest
finished
$ reana-client workflow status --name mythirdtest
$ reana-client outputs list --workflow mythirtest
$ reana-client workflow status
$ reana-client outputs download plot.png
$ reana-client workflow destroy
```

**Comment by diegodelemos** [comment]
Niquel! Closing since we all agreed 🎊
