### ISSUE TITLE
schemas: workflow type should be restricted to the known values

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#220]
Currently, the [workflow type in REANA yaml schema is a string](https://github.com/reanahub/reana-client/blob/master/reana_client/schemas/reana_analysis_schema.json#L133), we should limit it to be one of CWL, Yadata or Serial.

**Comment by diegodelemos** [comment]
The database model should be updated accordingly, see https://github.com/reanahub/reana-db/issues/23.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/commit/6575fa67d92164e2e23dfeea60e576b65eacc756
