### ISSUE TITLE
cli: eval on create

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#226]
it would be nice if in the cli one could have an option such that the REANA_WORKON is already set

similar to how in `$(openstack cluster config)`

perhaps one could have

```
eval $(reana-client create my-analysis --stdout)
```

**Comment by tiborsimko** [comment]
It is already possible, the `reana-client` returns precisely the good string for `REANA_WORKON` variable, so that one can do:

```console
$ export REANA_WORKON=$(reana-client create)
```
