### ISSUE TITLE
api: allow workflow creation with just workflow JSON

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#228]
We need to offer the Python API so CAP can submit workflows with just [workflow `json` specifications](https://github.com/reanahub/reana-demo-root6-roofit/tree/master/workflow) and not the `reana.yaml`.

Currently we offer and [endpoint in REANA-Server](https://reana-server.readthedocs.io/en/latest/_static/api.html#operation/create_workflow) which takes among other parameters a REANA specification which acts as an "envelope" and contains a resolved [reference](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/reana-yadage.yaml#L9) to the [workflow spec](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/workflow/yadage/workflow.yaml). This reference is [resolved and validated by `reana-client`](https://github.com/reanahub/reana-client/blob/master/reana_client/utils.py#L65-L69).

Currently we only have the following, which implies knowing about `reana.yaml`:

```python
create_workflow(reana_specification, name, access_token)
```

We should also offer something like the following, so CAP which only has workflow `json` can create CC @pamfilos :

```python
create_from_workflow_json(workflow_json, workflow_parameters, name, access_token)
```

Which could use the same [endpoint](https://reana-server.readthedocs.io/en/latest/_static/api.html#operation/create_workflow) and create on the client side a `reana.yaml` to wrap the workflow spec.

Observations:
- On current implementation, [we load and validate the workflow `json`](https://github.com/reanahub/reana-client/blob/master/reana_client/utils.py#L65-L69), if we get directly the workflow we have two options:
    - We validate it again
    - We let it pass assuming that CAP and other clients will pass valid CWL, Yadage or Serial workflows. In the case of a wrong `json` specification being submited a new batch engine will be spawned and it will fail which the corresponding waste of resources.
- We should take into account the possibility of submiting with differnt parameters.

**Comment by roksys** [comment]
@pamfilos, could you give an example of workflow_json that CAP will pass to REANA?
