### ISSUE TITLE
validation: update yadage schema version

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#251]
Hi, there have been some updates on the yadage end for the schemas and it would be good to update the yadage-schema version to `0.0.10` (as well as update the engine) -- should I submit PRs to both?

**Comment by tiborsimko** [comment]
Yes, please do.  We try to keep the same versions everywhere, for example for `yadage-schemas` see:

```console
$ grep yadage-schemas r*/setup.py
reana-client/setup.py:    'pyOpenSSL==17.5.0',  # FIXME remove once yadage-schemas solves deps.
reana-client/setup.py:    'rfc3987==1.3.7',  # FIXME remove once yadage-schemas solves deps.
reana-client/setup.py:    'strict-rfc3339==0.7',  # FIXME remove once yadage-schemas solves deps.
reana-client/setup.py:    'webcolors==1.7',  # FIXME remove once yadage-schemas solves deps.
reana-client/setup.py:    'yadage-schemas==0.7.16',
reana-server/setup.py:    'pyOpenSSL==17.5.0',  # FIXME remove once yadage-schemas solves deps.
reana-server/setup.py:    'rfc3987==1.3.7',  # FIXME remove once yadage-schemas solves deps.
reana-server/setup.py:    'strict-rfc3339==0.7',  # FIXME remove once yadage-schemas solves deps.
reana-server/setup.py:    'webcolors==1.7',  # FIXME remove once yadage-schemas solves deps.
reana-workflow-engine-yadage/setup.py:    'pyOpenSSL==17.5.0',  # FIXME remove once yadage-schemas solves deps.
reana-workflow-engine-yadage/setup.py:    'rfc3987==1.3.7',  # FIXME remove once yadage-schemas solves deps.
reana-workflow-engine-yadage/setup.py:    'strict-rfc3339==0.7',  # FIXME remove once yadage-schemas solves deps.
reana-workflow-engine-yadage/setup.py:    'yadage-schemas==0.7.16',
reana-workflow-engine-yadage/setup.py:    'webcolors==1.7',  # FIXME remove once yadage-schemas solves deps.
reana-workflow-monitor/setup.py:    'yadage-schemas==0.7.16'
```

It'll be good to fix this SSL issue at the same time.

P.S. It would be great to upgrade the Yadage engine as well, note that REANA is using 0.13.5 while you have released 0.19.2 already... Do you foresee many incompatible changes? It would be great if you can submit a PR for `r-w-e-yadage`.

**Comment by irinaespejo** [comment]
Hi, I'm also interested in updating yadage-schemas  to  something like `0.10.*`  in reana-client. I'm using a workflow that needs input parameters from the `init` step at almost every step (to give flexibility to the user). This workflow validates locally with yadage-schemas `0.10.2` but it doesn't with `0.7.16`. Therefore, when I run it from reana-client `0.4.0` and `0.5.0.dev20190220`, the validation fails and the workflow is not created. 
Let me know if log files or a mwe would be useful for you. Thanks!

I'm using reana-client `0.4.0` and have tried the '0.5.0` developer preview and

**Comment by cranmer** [comment]
Hello... I'd just like to +1 this... this impacts one of our workflow use cases for what we would like to use to showcase REANA with MadMiner: https://github.com/johannbrehmer/madminer

**Comment by tiborsimko** [comment]
@lukasheinrich Will you manage to find time to take care of upgrading Yadage?  We plan to wrap up the release of REANA v0.5.0 within a couple of weeks, it would be good if this can go in before.

**Comment by dprelipcean** [comment]
Upgrading yadage and removing the unnecessary packages PR group is ready to review and test:
https://github.com/reanahub/reana-client/pull/313
https://github.com/reanahub/reana-workflow-engine-yadage/pull/122
https://github.com/reanahub/reana-workflow-monitor/pull/29
https://github.com/reanahub/reana-server/pull/167

I have tested with the `roofit` and `helloworld` examples only.
