### ISSUE TITLE
cli: workflows becomes list

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#253]
Now that we have `ls` (and `du/mv/rm`) for file manipulation commands, the command name `list` liberated itself, as it were, and it is not used for anything.

While we could see about it being used as a click alias for `ls`, it would seem natural to use the name `list` to list all user's workflows instead.

See #252 for how the command overview looks when grouped thematically. `list` fits better there than `workflows`.  

P.S. Saw a user typing `list` expecting to get the list of workflows...

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-client/pull/267.
