### ISSUE TITLE
cli: setup-environment

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-client#304]
## What happens?

When restarting my machine, and trying to `reana-dev setup-environment` to get the environment variables, I get the error:

```
Environment variables could not be generated: 
HTTPSConnectionPool(host='192.168.39.111', port=8443): Max retries exceeded with url: /api/v1/nodes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f728e908f10>: Failed to establish a new connection: [Errno 113] No route to host',))
```
After running `minikube stop` and `minikube start,` the error changes to:

```
Environment variables could not be generated: 
Command '['kubectl', 'exec', '-t', u'db-54c5c6cb84-kvwph', '--', 'psql', '-U', 'reana', 'reana', '-c', 'SELECT access_token FROM user_']' returned non-zero exit status 1
```
or
```
Environment variables could not be generated: 
Command '['kubectl', 'exec', '-t', u'db-54c5c6cb84-xfgc2', '--', 'psql', '-U', 'reana', 'reana', '-c', 'SELECT access_token FROM user_']' returned non-zero exit status 2
```

## Fix
I found that a workaround is to run `make setup`. Afterwards, everything runs smoothly and the environment variables are generated.

## Feature request (?)
It would be nice not to have to run `make ci` every time. Maybe it's something in my own configuration that is set up badly?

**Comment by tiborsimko** [comment]
Note that since this concerns `reana-dev`, it'd better to open issues like this in the `reana` repository where that script lives.

**Comment by diegodelemos** [comment]
Moved to https://github.com/reanahub/reana/issues/208.
