### ISSUE TITLE
cli: loglevel command not working properly

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-client#315]
Sometimes it's useful to set the `loglevel` to `DEBUG`(or `INFO` for that matter) to get more info, but I get the following error:

```console
$ reana-client --loglevel DEBUG
Usage: reana-client [OPTIONS] COMMAND [ARGS]...
Try "reana-client --help" for help.

Error: Missing command.
```
but:
```console
$ reana-client --loglevel
Error: --loglevel option requires an argument
```
Maybe there's a small bug in the `click API`?

**Comment by tiborsimko** [comment]
You do need to supply a command to test it, for example:

```console
$ reana-client --loglevel DEBUG version
0.6.0.dev20190826
```

**Comment by dprelipcean** [comment]
Indeed, that is correct. Maybe we could add a command like `set-log-level' that actually changes the 'REANA_LOG_LEVEL` globally.
