### ISSUE TITLE
cli: "root path does not exist"

### ISSUE THREAD

**Issue by DBustamante98** [reanahub/reana-client#317]
Good day,

I am currently having a problem creating a workflow:
```
$ reana-client create
Workflow could not be created:
root path does not exist
```

The problem persists when using other `reana-client` options:
```
$ reana-client list
Workflow list could not be retrieved:
root path does not exist
```

Any idea how to fix it?

**Comment by roksys** [comment]
Hello @DBustamante98,

Which cluster do you use? How it is deployed?

Could you try to ping the cluster?

`$ reana-client ping`

**Comment by roksys** [comment]
Hello @DBustamante98,

Sorry for late reply, @diegodelemos just fixed it. Could you give a try?

**Comment by DBustamante98** [comment]
It is working again.

Thanks!
