### ISSUE TITLE
cli: improve list and status filtering

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-client#349]
At the moment `reana-client status --filter TEXT` always returns the value from the first column.

```console
$ reana-client status -w worldpopulation.serial                 
NAME                     RUN_NUMBER   CREATED               STATUS     PROGRESS
worldpopulation.serial   1            2020-01-13T17:13:06   finished   1/1     

$ reana-client status -w worldpopulation.serial --filter status 
STATUS                
worldpopulation.serial
```

However, when used with `--json` flag it displays the right value:
```console
$ reana-client status -w worldpopulation.serial --filter status --json   
[{"status": "finished"}]
```
---
On the other hand, `reana-client list` has a similar flag but called `--format` which has a more advanced functionality as one can filter based on the value in addition to the column name.

```console
$ reana-client list                                    
NAME                     RUN_NUMBER   CREATED               STATUS  
myworkflow               1            2020-01-13T17:46:28   created 
worldpopulation.serial   1            2020-01-13T17:13:06   finished
helloworld.yadage        1            2020-01-13T17:42:23   finished

$ reana-client list --format name,status=created       
NAME         STATUS 
myworkflow   created
```
The idea is unifying the functionality of both commands (and check if there are other similar cases), ideally having the logic behind `reana-client list --format` as it can be more useful for the user.

**Comment by tiborsimko** [comment]
:+1: for centralising on the more advanced formatting-with-filtering functionality, even though some commands may not really need it if they produce only one row. 

Having he same CLI option everywhere will simplify life for end users. 

Note that `--filter` seems to be only used in the `status` command, so replacing it there should suffice.

**Comment by roksys** [comment]
Closed by https://github.com/reanahub/reana-client/pull/352 & https://github.com/reanahub/reana-commons/pull/159
