### ISSUE TITLE
cli: rerun workflow in the same workspace

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#355]
We shall implement https://github.com/reanahub/reana-client/issues/202#issuecomment-441049790 which is the first approach of `reana-client workflow continue` command but in a more simple way, allowing `reana-client run` to be called multiple times instead of creating a new command. In order to tackle this we should take into account:

(1) Currently, we have embedded logic determining whether a workflow can be change to running or stopped in [two functions `_start_workflow` and `_stop_workflow`](https://github.com/reanahub/reana-workflow-controller/blob/01c6402d4bf76341a05b8bc5f59b04d5e10037cd/reana_workflow_controller/rest.py#L1824-L1861). In the case of rerunning, we would need to allow the transition `[finished|failed] -> [running]`, however in our codebase we only allow a workflow to be run if it is in state `created` or `queued`, see the following snippet or the code [here](https://github.com/reanahub/reana-workflow-controller/blob/01c6402d4bf76341a05b8bc5f59b04d5e10037cd/reana_workflow_controller/rest.py#L1826):

```python
...
    if workflow.status in [WorkflowStatus.created, WorkflowStatus.queued]:
        # start workflow code
...
```

To address the new rerun functionality, we can either:
- Patch it there, in [`_start_workflow`](https://github.com/reanahub/reana-workflow-controller/blob/01c6402d4bf76341a05b8bc5f59b04d5e10037cd/reana_workflow_controller/rest.py#L1824)
- Do more deep work and solve the existing ticket ["state: use state machine to manage workflow state"](https://github.com/reanahub/reana-workflow-controller/issues/149) and then, on top, add the new rule.

(2) Until now we have only covered RWC part. Regarding the specific workflow engines, regardless of the approach (1) or (2), we will face different challenges depending on the workflow engine implementation, for example, if you try to run yadage twice you get:

```console
$ yadage-run . workflow/yadage/workflow.yaml -p sleeptime=0 -p inputfile=data/names.txt  -p helloworld=code/helloworld.py -d initdir=`pwd`/yadage-inputs 
2020-01-16 14:56:34,688 | packtivity.asyncback |   INFO | configured pool size to 12
Error: Workflow failed: yadage meta directory ./_yadage/ exists. Allow overwrite by using the command line option  --accept-metadir
```

Actions:
- [ ] Allow to call `run` more than one time by solving (1) in RWC
- [ ] Solve (2) for `reana-workflow-engine-serial`
- [ ] Solve (2) for yadage? @lukasheinrich
- [ ] Solve (2) for CWL or ticketise for later

**Comment by tiborsimko** [comment]
Usage scenario: 

```console
$ reana-client create -w roofit
roofit.42
$ reana-client run -w roofit.42
<step gendata OK>
<step fitdata FAILS>
$ reana-client logs -w roofit.42 # read logs to see C++ exception
$ vim code/fitdata.C # fix the problem locally
$ reana-client upload code/fitdata.C -w roofit.42 # update run 42 workspace
$ reana-client start --restart -o FROM fitdata -w roofit.42 # restart from last failure
<fitdata OK>
$ git commit -a -s -m 'fitdata: exception fix'
```

In order to prevent user errors, the `start` command does not currently allow to restart either "finished" or "failed" workflows.  We could keep this behaviour as default of the `start` command, and require users to supply an additional option like `--restart` in order to trigger workflow restart regardless of the workflow state.  (Kind of like "yes I know what I am doing".)

P.S. Using `roofit.42` above, i.e. including run number, in order to prevent possible mishaps. However I guess `--restart` is a hard-enough thing to supply so that using `-w roofit` with its usual meaning "use the last run number of the roofit workflow" should also be acceptable.
