### ISSUE TITLE
cli: deleting "seemingly-running" workflows

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#360]
If something fails for a reason or another, the workflow may still be reported as running:

```console
$ reana-client status -w Htt.1
NAME   RUN_NUMBER   CREATED               STATUS    PROGRESS
Htt    1            2020-01-14T16:13:02   running   1/4    
```

even if there are no pods anymore.

In this case, it is impossible for the user to "stop" the workflow or to "delete" it:

```console
$ reana-client stop -w Htt.1 --force
Workflow could not be stopped: 
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 20 Jan 2020 16:52:46 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch \"fd28e4b2-ca9d-4050-bf58-71ab83e5ed13\" not found","reason":"NotFound","details":{"name":"fd28e4b2-ca9d-4050-bf58-71ab83e5ed13","group":"batch","kind":"jobs"},"code":404}
$ reana-client delete -w Htt.1 --include-workspace --include-all-runs
Workflow could not be deleted: 
Workflow Htt.1 cannot be deleted as it is currently running.
```

We should offer a way for the end user to terminate such a "seamingly-running" workflow say via `--force` option.

**Comment by diegodelemos** [comment]
I am completing this issue as currently I am working on https://github.com/reanahub/reana-workflow-controller/pull/310 and I have it fresh:

This issue can be split into two problems:
1. A workflow engine "dies" being the latest reported status `running`, so workflow controller assumes it is still running, and so it will be "forever":

    (a) If we can associate a Kombu producer with the REANA workflow id and listen to the event of disconnection then we can amend the database correctly. If this isn't possible, the `heartbeat` pattern should help, we might be able to (b) use [Kombu connection with a certain `heartbeat` rate](https://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.connection.html#connection) and use [`check_heartbeat()`](https://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.connection.html#kombu.connection.Connection.heartbeat_check) so if a workflow is running but we stop receiving the heartbeat we mark it as failed. I currently see (a) and (b) but there might be other solutions.

2. When a workflow is reported to be running but there are no workflow engines running in Kubernetes (regardless of the reason), and `reana-client stop --force` is called, we try to remove a resource that doesn't exist (the workflow engine pod):

    We should detect that there are no resources (`404` error from Kubernetes API server) warn the user about the situation and finalise the operation in the database.

**Comment by tiborsimko** [comment]
Besides addressing the cluster resilience (so that this won't even occur), it would be good to also address the 2nd part that you mention (because if it does occur for some reason, the user is not able to do anything):

```console
$ reana-client stop -w myanalysis.42 --force
Cannot stop workflow myanalysis.42: 
Workflow 1111-2222-3333-4444 could not be stopped.
```
