### ISSUE TITLE
cli: `logs` for given workflow step 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#369]
The `logs` command output may be significant in case a workflow has many steps.

It will be useful to allow getting outputs of some particular step, for example:

```
$ reana-client logs -w bsm --step select_signal_hist_0
```

(stems from #348)

**Comment by diegodelemos** [comment]
PR group reviewed and fully working, just one comment https://github.com/reanahub/reana-client/pull/376#discussion_r377545623 and one missing change from previous review https://github.com/reanahub/reana-workflow-controller/pull/297#discussion_r377547908. Once updated ready to integrate and deploy.
