### ISSUE TITLE
cli: `list` and `status` to inform about start/stop times

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#370]
**Current behaviour**

The `list` and `status` commands return only the workflow creation date:

```
$ reana-client list
NAME                  RUN_NUMBER   CREATED               STATUS
root6-roofit-yadage   1            2020-02-07T10:54:59   finished
root6-roofit-serial   1            2020-02-07T10:54:15   finished
root6-roofit-cwl      1            2020-02-07T10:53:36   finished
$ reana-client status -w root6-roofit-cwl
NAME               RUN_NUMBER   CREATED               STATUS     PROGRESS
root6-roofit-cwl   1            2020-02-07T10:53:36   finished   2/2
```

This is OK for queued workflows, but if a workflow started or if it has finished, it'll be useful to expose start up time and finished time as well.

**Expected behaviour**

The `status` command should definitely return start/stop times: 

```
$ reana-client status -w root6-roofit-cwl
NAME               RUN_NUMBER   CREATED               STARTED              STOPPED               STATUS     PROGRESS 
root6-roofit-cwl   1            2020-02-07T10:53:36   2020-02-07T10:53:36  2020-02-07T10:53:36   finished   2/2
```

The `list` command could do as well since it is not too expensive (=the same DB lookup).

We could call the new output columns STARTED (this one is easy) and STOPPED (this one is harder, "stopped" would be the mirror-word to "started", but it may not be the best, as its meaning can be misinterpreted).  The "finished/completed/etc" column name should fit both "finished" and "failed" workflows, so we should find something generic.  Could even use "begun/ended" or somehing... Muse more IRL when this task is taken up.

**Comment by roksys** [comment]
HTCondor has a ``COMPLETED `` column, we could use it as well? @tiborsimko WDYT?

```
ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD  
4156852.128  user          2/9  22:36   0+02:00:12 X         ???  some cmd
4156855.454  user          2/9  22:37   0+01:23:18 C   2/10 01:02 some cmd
```

**Comment by tiborsimko** [comment]
Yes, `COMPLETED` sounds like a nice neutral term describing both "finished" and "failed" ones :+1:

**Comment by diegodelemos** [comment]
Some musings regarding how to show this information:

Using `COMPLETED` will introduce a new term, what is completed? I would expect to see `COMPLETED` if the workflow finished correctly, however I would expect `FAILED` for the failed ones
```console
$ rc list                                                                                                                                                   [3:32:52]
NAME       RUN_NUMBER   CREATED               STARTED               COMPLETED            FAILED                STATUS  
workflow   18           2020-02-10T14:32:18   2020-02-10T14:32:21   -                    2020-02-10T14:32:39   failed  
workflow   17           2020-02-10T14:31:39   2020-02-10T14:31:41   2020-02-10T14:32:00                        finished
workflow   16           2020-02-10T14:22:23   2020-02-10T14:22:25   2020-02-10T14:22:44                        finished
test       1            2020-02-10T12:47:04   -                     -                    -                     created 
workflow   15           2020-02-10T12:46:30   2020-02-10T12:46:33   2020-02-10T12:46:51                        finished
workflow   14           2020-02-10T12:36:36   2020-02-10T12:36:39   2020-02-10T12:36:50                        finished
```
Since this just adds more complexity for the user I don't think it is feasible.

On the other hand, using `FINISHED` instead of `COMPLETED` would imply, in my eyes, that the workflow has ended in `finished` state. If we would change the status to `succeeded` `FINISHED` column name would do the job:
```console
$ rc list                                                                                                                                                   [3:32:52]
NAME       RUN_NUMBER   CREATED               STARTED               FINISHED              STATUS  
workflow   18           2020-02-10T14:32:18   2020-02-10T14:32:21   2020-02-10T14:32:39   failed  
workflow   17           2020-02-10T14:31:39   2020-02-10T14:31:41   2020-02-10T14:32:00   succeeded
workflow   16           2020-02-10T14:22:23   2020-02-10T14:22:25   2020-02-10T14:22:44   succeeded
test       1            2020-02-10T12:47:04   -                     -                     created 
workflow   15           2020-02-10T12:46:30   2020-02-10T12:46:33   2020-02-10T12:46:51   succeeded
workflow   14           2020-02-10T12:36:36   2020-02-10T12:36:39   2020-02-10T12:36:50   succeeded
```

Just writing this down because of the musings about changing the status name `finished` -> `succeeded`, I will go for `COMLETED` for now.

**Comment by tiborsimko** [comment]
> I would expect to see COMPLETED if the workflow finished correctly

Late-night musings:

In my eyes, not necessarily; I read it as an "execution completed", which can apply to both successfully completed executions ("finished") and unsuccessfully completed executions ("failed").

(In any case, introducing a new column FAILED would not be good interface-wise; it is better to stick to a fixed number of columns, especially since the status of the successful/unsuccessful workflows is already clear from the STATUS column.)

Perhaps we can think of another term if COMPLETED looks too positive in your eyes? Perhaps ENDED?  The combination STARTED/ENDED and finished/failed reads OK in my eyes.

That said, going for FINISHED column name and "succeeded" status would also do nicely in my eyes. Albeit it would be a bigger change touching more of the code base, which I wanted to avoid.... However if you feel like doing so, then I'd say let's go for it :+1: The combination STARTED/FINISHED and succeeded/failed reads even better in my eyes.

**Comment by diegodelemos** [comment]
`ENDED` looks better to me 👍. Regarding changing the status name to `succeeded`, as you mention it would bring a lot of uncertainty right now, which might not be the best moment.
