### ISSUE TITLE
yadage: make initdir configurable

### ISSUE THREAD

**Issue by danikam** [reanahub/reana-client#396]
For workflows running over local (rather than downloadable) input, such as the [current monojet workflow](https://gitlab.cern.ch/damacdon/workflow_monojet) (see [run instructions](reana_workflow_engine_yadage/cli.py#L104)), the yadage `-d initdir=` option is currently hardcoded in [reana_workflow_engine_yadage/cli.py#L104](https://github.com/reanahub/reana-workflow-engine-yadage/blob/f5e88cb186428b4c885f0717b6739758a1d2c436/reana_workflow_engine_yadage/cli.py#L104) (thanks to @tiborsimko for identifying this). Could this become configurable in reana.yaml?

**Comment by mvidalgarcia** [comment]
Hi @danikam I don't have access to the links you posted:
- https://gitlab.cern.ch/atlas-phys/exot/jdm/ANA-EXOT-2018-06/workflow
- https://github.com/reanahub/reana-client/issues/reana_workflow_engine_yadage/cli.py#L104

Could you update them or paste an example?

**Comment by danikam** [comment]
Hi @mvidalgarcia, sorry about that and thanks for letting me know! 

I copied the monojet gitlab repo over to a public one, here's the link to it: https://gitlab.cern.ch/damacdon/workflow_monojet

And here's the correct link to the line in the cli.py: https://github.com/reanahub/reana-workflow-engine-yadage/blob/master/reana_workflow_engine_yadage/cli.py#L104
