### ISSUE TITLE
cli: reana-client run looks for input files in reana.yaml

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-client#403]
Regardless what reana file name you pass in using `-f` it always tries to get the input files from a `reana.yaml` file.

**Current result**

```console
$ reana-client run -f my-reana.yaml -w test         
[INFO] Creating a workflow...
test.1
[INFO] Uploading files...
==> ERROR: No REANA specification file (reana.yaml) found. Exiting.
```

**Expected result**
```console
$ reana-client run -f my-reana.yaml -w test         
[INFO] Creating a workflow...
test.1
[INFO] Uploading files...
File code/gendata.C was successfully uploaded.                                                                                
File code/fitdata.C was successfully uploaded.  
[INFO] Starting workflow...
test.1 has been queued
```

**Comment by tiborsimko** [comment]
Let's check also `upload`... Ideally, once a user specifies `create -n myanalysis -f myreana.yaml`, this should set the workflow `myanalysis` to use the given file, so ideally this should be possible:

```console
$ reana-client create -w myanalysis -f something.yaml
$ reana-client upload -w myanalysis.42
```

This would require that reana-client asks REANA server "what is the spec file for workflow myanalysis.42?" or "what are the inputs to upload for workflow myanalysis.42?", so some client<->server back and forth may be needed.  (Kind of like for the future download feature #179)
