### ISSUE TITLE
cli: outdated reana-commons API ref.

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana-client#417]
When testing the installation of a local REANA cluster using [the latest documentation](http://docs.reana.io/development/deploying-locally/), and the current development version of all repositories (`v0.7.0-dev...`) I ran into an issue.

### The problem
When executing:
```shell script
eval $(reana-dev setup-environment)
reana-client ping
```

An error is shown describing that the `SERVER IS INVALID`.

### The solution

I think it is due to [this `reana-commons` refactor](https://github.com/reanahub/reana-commons/commit/3a10925c4450b5e9ae8116dfc555955a93d0a00c), where the endpoint `/get_me` was replaced by `/get_you`. This endpoint seems to be used internally by [reana_client.api.client.py](https://github.com/reanahub/reana-client/blob/master/reana_client/api/client.py) when performing the `ping` operation (more precisely, in [this line](https://github.com/reanahub/reana-client/blob/master/reana_client/api/client.py#L38)).

### The test
I have uninstalled `reana-client` from my local environment and installed a locally modified version with the patch, set up the environment variables again, and the `ping` command worked as expected.

**Comment by mvidalgarcia** [comment]
@Sinclert Thanks for the report! 👍  You're totally right! As you have the patch already, could you create a PR? Otherwise we can do it, no problem, let us know.

**Comment by Sinclert** [comment]
I can propose a PR right away, bumping the version too.
