### ISSUE TITLE
cli: implement filtering by status and search by name

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-client#427]
We already have the [filtering/search logic server-side](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/rest/workflows.py#L207-L215). The idea will be adding options to `reana-client list` that allows filtering by status and searching by workflow name.
Sorting by creation date is already possible locally via `reana-client list --sort CREATED`. However, if pagination is used, this won't work properly as it only will sort the page itself.

**Comment by tiborsimko** [comment]
See also how we implemented filtering of logs:

```console
$ reana-client logs --help
...
  --filter TEXT            Filter job logs to include only those steps that
                           match certain filtering criteria. Use --filter
                           name=value pairs. Available filters are
                           compute_backend, docker_img, status and step.
```

We could do the same for the `list` command, something like:

```console
$ reana-client list --filter name=roofit
$ reana-client list --filter status=running
$ reana-client list --filter name=roofit --filter status=deleted
```

**Comment by ParthS007** [comment]
@tiborsimko This filtering by status and search by name is for workflow. Right?

**Comment by tiborsimko** [comment]
Yeah, that should be sufficient.  We have others in the output (e.g. see `reana-client list -v`) but it would be unusual to filter by those... Except perhaps run number.

P.S. Here you can safely use `contains` to match workflow name substrings :wink: unlike in `cernopendata-client` where we needed to match exactly.

P.P.S. After this is done, it would be great to add similar filtering (for file names) into `reana-client ls -w roofit.1 --help` but let's make another issue for that. Mentioning this just to "think ahead" of what will come in the unification of the output filtering capabilities and CLI options...
