### ISSUE TITLE
cli: Improve the cosmetics of output messages

### ISSUE THREAD

**Issue by ParthS007** [reanahub/reana-client#431]
Yes, as we do for the `logs` command already:

```console
$ reana-client logs -w helloworld-yadage --filter staaatus=foo
Error: filter 'staaatus' is not valid.
Available filters are 'compute_backend' 'docker_img' 'status' 'step'.
```

We can unify the formatting at least for the various `--filter` commands everywhere.

BTW note that the output message formatting cosmetics will remain elsewhere to be amend as well, for example in `ping` we don't report it either:

```console
$ reana-client ping
REANA client is not connected to any REANA cluster.
```

Something for another issue. We have quite a potential to improve cosmetics regarding `==> ERROR: ...` and friends.

_Originally posted by @tiborsimko in https://github.com/reanahub/reana-client/pull/428#discussion_r504760350_

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/553, thanks to @Sinclert 👍
