### ISSUE TITLE
cli: enrich `ping` command with version information

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#441]
Currently, the `ping` command returns:

```console
$ reana-client ping
REANA server: https://reana-qa.cern.ch
Authenticated as: John Doe <john.doe@example.org>
Status: Connected
```

Some users were experiencing troubles in the past mixing old REANA client version with new REANA server deployments.

It would be therefore good to output also the client/server version information in the `ping` command, similarly to `kubectl`.

Example:

```console
$ reana-client ping
REANA server: https://reana-qa.cern.ch
REANA server version: 0.8.0a1
REANA client version: 0.7.0
Authenticated as: John Doe <john.doe@example.org>
Status: Connected
```

We should also emit a big warning in case the client and the server versions do not match and are expected to be incompatible, e.g. client/0.6.0 and server/0.7.0.

For now, we may require the same 0.X.* minor version.

If we detect incompatibilities, we could also display `pip` instructions how to upgrade the client, or simply link to the docs.

**Comment by mvidalgarcia** [comment]
> We should also emit a big warning in case the client and the server versions do not match and are expected to be incompatible, e.g. client/0.6.0 and server/0.7.0.

Hard to tell, as there might be incompatible versions even sharing the same mayor/minor version.

**Comment by diegodelemos** [comment]
I wonder whether we should have a different command to display versions as `kubectl` does (`kubectl version`). This would also touch the fact that `/api/you` fields are growing in complexity and are very different responsibility wise.

**Comment by tiborsimko** [comment]
> Hard to tell, as there might be incompatible versions even sharing the same mayor/minor version.

Well, we respect major.minor.patchlevel versioning philosophy, so we shouldn't introduce breaking changes between client and cluster within the same `0.x.*` family.  That's what I meant to check for as an MVP, where `0` and `x` are the same, regardless of the patchlevel version. 

Ideally, as we discussed live in the past, each REST API endpoint output should send its "version" back in the reply, either in the body or in X header, so that the client should decide "aha, this disk information output is version 0.7, so I won't activate inode counting branch for the user".  But this is only coming later...

> I wonder whether we should have a different command to display versions as kubectl does (kubectl version)

We already have `reana-client version` command, but this one works only for client, it does not query the server. It could, though.

The thinking for doing this in the `ping` command is that we are advertising this command to the users in order to check their general connectedness health, including user token validity, so that people have basically one single place to ask "am I well connected?". Displaying any errors we know of right there would be helpful for them.

P.S. As mentioned above, ideally each `r-client` would support each `r-server` version, even if sometimes printing "please upgrade" if the server is too new... But it will take time to have this, so until we are there, it is of great help to indicate to users that their client version is not compatible with the server they are trying to connect to; the sooner the better.
