### ISSUE TITLE
validate: verify possibly dangerous operations

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#458]
Building up on previous tasks of verifying environment images, see #457 for example, we can take validation further to perform some sanity checks on the workflow commands.

For example, it happened that a workflow was running `sudo /some/command/...` all the while asking to run the job as some kubernetes_uid. We should warn the user about these cases.

For example, the `validate --steps` could run a quick `grep` looking for `sudo`, and report findings.

Another example, operations like `cd /some/path` may be dangerous, if there is a future cp/wget/xrdcp` populating some internal directory hard-coded inside the container image, and not populating the usual workspace directory, with input files. We could do a quick grep helping to spot these situations.

IOW, we are not looking for the perfect solution, but a good first approach to catching these early on the reana-client side.

(E.g. the writing-to-local-ephemeral-storage situation will be best caught by the REANA platform on the server side, but that will become another issue.)

===

**Current status:**

- [x] Serial - https://github.com/reanahub/reana-client/pull/471
- [x] Yadage - https://github.com/reanahub/reana-client/pull/470/commits/9c886a1c11cc3524a2c9525e8a8850f2736e5aaf
- [x] CWL - https://github.com/reanahub/reana-client/pull/481

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/481
