### ISSUE TITLE
validate: local environment image validation mode

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#475]
**Current behaviour**

If you would like to validate environment images for an analysis and you don't have the image available locally, then the validation attempts to download the image, assuming active network:

```console
$ reana-client validate --environments 
==> Environment image reanahub/reana-env-root6:6.18.04 has correct format.
==> Environment image reanahub/reana-env-root6:6.18.04 exists.
Unable to find image 'reanahub/reana-env-root6:6.18.04' locally
6.18.04: Pulling from reanahub/reana-env-root6
7ddbc47eeb70: Pulling fs layer
c1bbdc448b72: Pulling fs layer
```

Similarly, if you are developing a new image, say Roofit `6.18.04.patch1`, then the image is not published to Docker Hub before it is "correct". Hence the test for image existence may be "knowingly failing":

```console
$ docker tag reanahub/reana-env-root6:6.18.04 reanahub/reana-env-root6:6.18.04.patch1
$ docker images | grep -i 6.18.04                                                    
reanahub/reana-env-root6                          6.18.04          c754f13f32ae   13 months ago    2.07GB
reanahub/reana-env-root6                          6.18.04.patch1   c754f13f32ae   13 months ago    2.07GB
$ sed -i 's,6.18.04,6.18.04.patch1,g' reana.yaml
$ reana-client validate --environments
==> Environment image reanahub/reana-env-root6:6.18.04.patch1 has correct format.
==> ERROR: Environment image reanahub/reana-env-root6:6.18.04.patch1 does not exist: Tag not found
```

**Expected behaviour**

In the former case, it may be good to inttroduce a CLI option named such as `--pull` that will not be on by default, so that users could use validation feature in say an airplane travel mode.

In the latter case, it may be good to detect that the image is available locally first.

IOW, this issue is calling for having a `--local` execution mode where local Docker registry is checked for everything, and "remote" execution mode where the remote Docker Hub (or GitLab, or...) would be checked.  (Optionally with `--pull` flag mentioned above.)

Note that for most people developing their own containers, the "local" mode will be the most important one.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/476
