### ISSUE TITLE
cli: list command does not incude deleted runs

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#482]
**Current behaviour**

Consider the following workflow run list:

```console
$ reana-client list -v                                                                     
NAME    RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     ID                                     USER                                   SIZE
hello   1            2021-03-18T23:57:21   2021-03-18T23:57:22   2021-03-18T23:59:25   finished   49315fd8-04f1-4e41-b8c3-200b51a862ca   00000000-0000-0000-0000-000000000000   100G 
```

The user deletes the run:

```console
$ reana-client delete -w hello                                                                     
hello has been deleted
```

Whoops! The user noticed 100G and would like to delete the workspace too, so the user lists workflows again:

```console

$ reana-client list           
NAME   RUN_NUMBER   CREATED   STARTED   ENDED   STATUS
```

The list is empty, so there is apparently nothing more to delete... and 100G leave hanging out.

Note that the user would still be able to do:

```console
$ reana-client delete -w hello.1 --include-workspace 
hello.1 has been deleted
```

which would delete the workspace just fine.

IOW, it still works to delete the workspace, but users don't see anymore that they have some workflows (with big disk usage) that they could delete.

(But they could see those using web UI.)

**Expected behaviour**

- Option 1: Include also deleted workflow runs in the `list` output by default. Advantage: people will see all their runs as in the web UI. Disadvantage: the output may be long. Would need a CLI option such as `--exclude-deleted`. (See also notes about filtering.)

- Option 2: Do not change semantics of the `list` command, i.e. do not show deleted workflows by default; however add a new CLI option `--include-deleted` that would also include those deleted workflow runs. Pros: shorter list. Cons: mismatch with web UI defaults on REANA 0.7 release series.

- Option 3: BTW, when deleting a workflow, consider deleting also its workspace by default. Pros: this may be the most natural thing to do; when a user wants to delete a workflow, it is very probable that the user wants to _also_ delete all its file. Pros: no hanging workspaces, behaving according to expectations. Cons: this would change current semantics, so it may be dangerous, unless we add some  confirmation option such as `--force`.

**Notes**

- Speaking of include/exclude options, we already have `--format` that could do `status=failed`. So we may have a part of the solution already by using `--format`.  However, for other commands such as `logs` we have `--filter`, which would be more natural thing to use here.  So, I'd vote for option 1, so that CLI and Web UI would behave identically, and offer some strong `--filter` option to remove undesirable lines.  Which would mean amending `--format` and `--filter` semantics here and for other commands. For example:

```console
$ reana-client list --format status,name,run_number --filter status=deleted,status=failed
```

would output all workflow runs which were either deleted or failed.

- If we do the above, we could consider flipping defaults to also include workspace deletion as part of REANA 0.8.

- MVP would be to do the option1, simply not to "hide" any runs from the user, and do the rest in REANA 0.8.

**Comment by ParthS007** [comment]
I prefer to keep the semantics same in the UI and the client, Option 1 goes with this.

**Comment by mvidalgarcia** [comment]
Note that there's already `--all` to list deleted workflow as well.

**Comment by tiborsimko** [comment]
True that, completely forgot about `--all`! :man_facepalming: Still, it would be good to keep the CLI UI and Web UI consistency (e.g. just flip the defaults and keep `--all` for backward compatibility) and to address the format-vs-filter differences (in `master`).

**Comment by ParthS007** [comment]
okay, I will do the same then. 

Just to confirm, The `flipping` of defaults has to be in `maint` branch and addressing of format-vs-filter in `master`?
