### ISSUE TITLE
client: error running workflows with spec file path using Python API

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-client#494]
> The Pythonic API allows creating workflows programmatically https://blog.reana.io/posts/2021/reana-client-python-api. However, it only works by creating workflows from JSON specs. This is not compatible with all workflow engines, for example Yadage uses [workflow specification file paths only](https://github.com/reanahub/reana-workflow-engine-yadage/blob/e20432b8d2c20e8c35fb53e4444f98b9612808cb/reana_workflow_engine_yadage/cli.py#L73-L78) as opposed to e.g. [Serial where only JSON specs are accepted](https://github.com/reanahub/reana-workflow-engine-serial/blob/b9219f631f327b6e1f45e66dbc1f6c364ce0e973/reana_workflow_engine_serial/tasks.py#L50-L54).

> This can be achieved by allowing running from workflow file; manually upload workflow file with `file_upload`; use the rest of the existing API, `create_workflow` (to be tested, documented etc...)

_Originally written by @diegodelemos_

**Comment by lukasheinrich** [comment]
if it requirers a workflow JSON that's fine too, but should be documented

```yadageschemas.load(....)``` should work

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-client/pull/495.

**Comment by mvidalgarcia** [comment]
Hi @lukasheinrich, if you install `reana-client` from GitHub, branch `maint-0.7`, you should be able to run Yadage workflows using the file spec path. I leave this example for reference: https://gist.github.com/mvidalgarcia/a1e61628dd67ed1a8b80d868684e1352

The main difference compared to the example in the blog post is that one needs to upload the `workflow/yadage` dir as it contains the spec file and `create_workflow_from_json()` call is a bit different (`workflow_json` vs `workflow_file`).
