### ISSUE TITLE
`upload_to_server` fails on empty list

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#500]
passing an empty ilst to `upload_to_server` seems to fail 

would be great if this could be handled gracefully (ffor automation tools)

**Comment by tiborsimko** [comment]
Currently we raise:

```
    537         raise ValueError("Workflow name or id must be provided")
    538     if not paths:
--> 539         raise ValueError(
    540             "Please provide path(s) to file(s) that " "should be uploaded to workspace."
    541         )
```

We could silently skip uploading if `paths` is a none-like object.

P.S. `def upload_to_server(workflow, paths, access_token)` in `reana_client/api/client.py`.
