### ISSUE TITLE
add `reana-client cat`

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-client#509]
sometimes it's convenient to be able to just dump the contents of a file to stdout (e.g. a JSON file) for this a `reana-client cat`  would be nice to have

**Comment by tiborsimko** [comment]
Yes, this may be interesting to have for small files. One option could be to introduce a new command `cat`, as you suggested. Another option could be to enrich the `download` command's `-o` option to allow specifying stdout stream for output, such as `download -w myanalysis myoutput.json -o -`.

(BTW, `ls` or `download` commands can work with multiple files, if these are given as argument, so we'd have to define how `cat` would work in such a scenario. Perhaps exactly like Unix's `cat` would do, not distinguishing what sources are concatenated together.)
