### ISSUE TITLE
cli: cannot stop queued workflow

### ISSUE THREAD

**Issue by alintulu** [reanahub/reana-client#557]
## Current behaviour

User is unable to stop a workflow that is queuing. The error message simply says "the workflow is not running" (see below for full example).

```
$ reana-client run -w workflow
$ reana-client list
NAME                 RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS
workflow             1            2021-09-07T12:34:16   -                     -                     queued
$ reana-client stop -w workflow
Graceful stop not implement yet. If you really want to stop your workflow without waiting for jobs to finish use: 
--force option
Aborted!
$ reana-client stop -w workflow --force
Cannot stop workflow workflow: 
Workflow 8dabbd83-04ec-4cb0-a48d-56d07e1d8869 is not running.
```

The user might realise that the submitted workflow is wrong. If so, the user has to wait until the workflow is running before being able to stop it (currently there is no way to know when the workflow starts to run).

## Expected behaviour

The command `reana-client stop` should also stop workflows in the queue.

**Comment by mvidalgarcia** [comment]
You can delete it:

```bash
# pip install reana-client==0.7.5
$ reana-client delete -w workflow --include-workspace --include-records
```

Does it have the same behaviour you're looking for?

**Comment by alintulu** [comment]
Ah, you're right! Thanks, that solves it :)
