### ISSUE TITLE
cli: seeding inputs and code with absolute paths

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#67]
Currently `reana-client code upload FILE` and `reana-client inputs upload FILE` expect as arguments filenames that are located in the `./code` and `./inputs` directories.  One cannot upload from another place:

```console
$ reana-client inputs upload ./README.rst 
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.99.100:32658
[INFO] Workflow "e4a3305b-a11f-401e-b836-eb426fc191dd" selected
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana-client/bin/reana-client", line 11, in <module>
    sys.exit(cli())
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/simko/.virtualenvs/reana-client/lib/python2.7/site-packages/reana_client/cli/inputs.py", line 155, in inputs_upload
    format(f.name),
UnboundLocalError: local variable 'f' referenced before assignment
```

However, using `code` and `inputs` subdirectories is simply a convention advising people how to structure their analyses.  It is very well possible that some people prefer working in a single workspace directory only, or that some people prefer calling their directories `data` (instead of `inputs`) and `src` (instead of `code`), etc.  

We should be agnostic to the naming people use, and translate their convention into REANA newspeak (that would continue using inputs and code internally).
 
This can be achieved by simply requiring `FILE` to be an absolute/relative path to the current working directory, not assuming anything about the required structure.  (An additional positive side outcome out of this would be that we wouldn't need `--inputs-directory` argument in this case, which would simplify simplify the function signature when someone runs `-help`.)

Some of the use case examples:

```console
# all these will upload to /reana/.../inputs/mydata.csv
$ reana-client inputs upload mydata.csv # look inside `inputs` subdir for backwards compatibility
$ reana-client inputs upload ./mydata.csv 
$ reana-client inputs upload ./data/mydata.csv 
$ reana-client inputs upload ./inputs/mydata.csv
$ reana-client inputs upload ./stuff/mydata.csv

# possible later extension to upload several files at once:
$ reana-client inputs upload ./mydata/*.csv

# beware of uploading files with leading subdirectories
$ reana-client inputs upload ./data/small-sample/mydata.csv
$ reana-client inputs upload ./data/big-sample/mydata.csv

# possible later extension to recursively upload everything
$ reana-client inputs upload -r ./inputs/*

# possible later extension for non-file-upload seeding
$ reana-client inputs upload http://example.org/mydata.csv
$ reana-client inputs upload root://example.org/mydata.csv
```

Note that using absolute/relative path for FILE will make a nice coherent picture with `reana.yaml` where we already use those paths:

```yaml
inputs:
  files:
    - inputs/names.txt
```

Someone preferring other nomenclature could use:

```yaml
inputs:
  files:
    - mydata/names.txt
```

and in CLI:

```console
$ reana-client inputs upload # seed everything listed in reana yaml file
$ reana-client inputs upload mydata/names.txt # as seen in reana yaml file
```

**P.S.** Note that some of the above use cases, such as the recursive upload of directories, will be for future milestones... It's simply good to keep all these various use cases in mind when we start refactoring the current inputs-name-is-hardcoded into the wanted inputs-name-is-optional behaviour.

**Comment by diegodelemos** [comment]
Agreed in general except for including directories:
> ```console
> # beware of uploading files with leading subdirectories
> $ reana-client inputs upload ./data/small-sample/mydata.csv
> $ reana-client inputs upload ./data/big-sample/mydata.csv
> ```

If we get rid of relative `inputs`/`code` directories from config or using `--inputs-directory` it won't be that easy to determine what are the desirable directories to include, for example:

```console
~ analysis_a $ reana-client inputs upload /home/johndoe/code/analysis_b/mydata/small-sample/mydata.csv
```
Clearly the user would like to upload `small-sample/mydata.csv` but we would perhaps upload `johndoe/code/analysis_b/mydata/small-sample/mydata.csv`.

I agree that wouldn't be a good practice, but I can see it easily happening.

**Comment by diegodelemos** [comment]
Actually, because of [this](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/rest.py#L375) we do not support directory uploads... we  use `werkzeug.secure_filename()`:

```console
>>> secure_filename("../../../etc/passwd")
'etc_passwd'
```
Which was changed by @anton-khodak [here](https://github.com/reanahub/reana-workflow-controller/pull/53/files#diff-3ee9faf1efe690830f3d86cb5d3cf590R383), retrieving only the file name.

It might be better to go for filename only for now... @tiborsimko @anton-khodak What do you think?

**Comment by tiborsimko** [comment]
> Clearly the user would like to upload small-sample/mydata.csv but we would perhaps upload johndoe/code/analysis_b/mydata/small-sample/mydata.csv.

We could solve this by `reana-client inputs upload fromdir:todir` kind of technique, almost like `git push someplace localbranch:remotebranch`.  (Well, it would a bit to low-level for peole to use, and not very use friendly... just an example to illustrate discussion.)  Right now we don't have to worry about subdirs in inputs as of yet. 

> It might be better to go for filename only for now.

Yes, I fully agree, that's why I mentioned plenty of "possible later extension" exmaples.   In the future, if `reana-client` sees a directory, it could zip it into a file, ship this zip file, and unzip it on the server side work space.  This would allow to seed any arbitrary subdirectory structures with out `fromdir:todir` kind of nightmare.  Anyway, this is again something we can muse later on.
