### ISSUE TITLE
cli: easier environment setting

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#73]
Currently, the setting of `REANA_WORKON` is not very straightforward:

```console
$ reana-client workflow create
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.99.100:32658
[INFO] Validating REANA specification file: /home/simko/private/src/reana-demo-root6-roofit/reana.yaml
[INFO] Connecting to http://192.168.99.100:32658
{u'message': u'Workflow workspace created', u'workflow_id': u'3be010aa-b3b5-408c-9d16-17f0518a6995'}
$ export REANA_WORKON=3be010aa-b3b5-408c-9d16-17f0518a6995
```
People have to parse the output of the `workflow create` command in order to extract the workflow ID in order to set up the `REANA_WORKON` properly.

Firstly, note that this will be alleviated by #70 if people choose some workflow name.  However, if people don't choose anything, the problem would still persist.

Secondly, the output should be less verbose #72 so that `[INFO]` comments are hidden.

This ticket is about creating the nicer output for `REANA_WORKON` command so that people could write something like:

```console
$ export REANA_WORKON=$(reana-client workflow create)
``` 

or one could imagine emulating `docker-machine` like behaviour more faithfully:

```console
$ eval $(reana-client workflow create)
```

which will be ready for more environment variables.

We could write:

```console
$ reana-client env
```

which would display all REANA_* environment variables that the user is currently using.  (Which would remove the need for the `[INFO]` lines mentioned above.) 

See also a related ticket for reana-cluster https://github.com/reanahub/reana-cluster/issues/55.

**Comment by tiborsimko** [comment]
Some other options option discussed during `CWL-Release` kick-off: 

- when there is only one workflow run created by the user, use that one
- cache things like the workflow "workon" run name on the client side in `~/.config/reana/` space
- `reana-client workflow create` would populate `~/.config/reana/` space

**Comment by tiborsimko** [comment]
For now, `reana-client workflow create` could simply output the UUID of the workflow run without any decorations, quite like `docker` is doing:

```console
$ docker run -d -p 80:80 -p 443:443 tiborsimko/invenio:1.2.2
8a6f328ee78e1dc9d5a89d4e29342d15a60d61a55ed36524b77f554ddcc37abe
```

This would permit the users to "emulate" workflow names in their shell environment as follows:

```console
$ mytestrun=$(reana-client workflow create)
$ export REANA_WORKON=$mytestrun
```

However the full support for providing wanted name (`-n ....`) is still preferable.

**Comment by dinosk** [comment]
This should be fixed by https://github.com/reanahub/reana-client/pull/81/files

**Comment by tiborsimko** [comment]
Yes, having the persistent workflow names wouldn't require to "emulate" them in the above way... Closing the issue.
